# Description: This file contains the pinout
# of the Raspberry Pi 4 Model B used in the project.
REDLED_PIN = 11
GREENLED_PIN = 17
YELLOWLED_PIN = 10

BUTTONENTER_PIN = 6
BUTTONUP_PIN = 19
BUTTONDOWN_PIN = 13
BUTTONBACK_PIN = 26

SCREENRS_PIN = 21
SCREENE_PIN = 16
SCREENRW_PIN = 20
SCREEND0_PIN = 12
SCREEND1_PIN = 7
SCREEND2_PIN = 8
SCREEND3_PIN = 25
SCREEND4_PIN = 24
SCREEND5_PIN = 23
SCREEND6_PIN = 18
SCREEND7_PIN = 15

SCREEN_DATABUS = [
    SCREEND0_PIN,
    SCREEND1_PIN,
    SCREEND2_PIN,
    SCREEND3_PIN,
    SCREEND4_PIN,
    SCREEND5_PIN,
    SCREEND6_PIN,
    SCREEND7_PIN,
]

CABLEGREEN_PIN = 4
CABLEPURPLE_PIN = 22
CABLEBLUE_PIN = 5
